**<h1>DAY 1</H1>**

---


Let's start with the Basics of Numpy Array.
<br>Creating a Numpy Array.

---



NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

---



In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


<h2>Dimensions in Arrays</h2>

---



<H3>0-D Arrays</H3>

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [2]:
import numpy as np

arr = np.array(11)

print(arr)

11


<H3>1-D Arrays</H3>
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
These are the most common and basic arrays.

In [3]:
import numpy as np

arr = np.array([2,4,6,8])

print(arr)

[2 4 6 8]


<H3>2-D Arrays</H3>
An array that has 1-D arrays as its elements is called a 2-D array.
These are often used to represent matrix or 2nd order tensors.

In [4]:
import numpy as np

arr = np.array([[2,5,6], [7,4,3]])

print(arr)

[[2 5 6]
 [7 4 3]]


<H3>3-D arrays</H3>
An array that has 2-D arrays (matrices) as its elements is called 3-D array.
These are often used to represent a 3rd order tensor.

In [5]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


<H3>Check Number of Dimensions?</H3>
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [6]:
a = np.array(11)
b = np.array([2,4,6,8])
c = np.array([[7,5,6], [2,5,8]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


<H3>Higher Dimensional Arrays</H3>
An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the ndmin argument.

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
