<H1><B>DAY 3</H1></B>

---



<H3>Slicing arrays</H3>

---


Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [2]:
import numpy as np

arr = np.array([2,3,4,5,2,3,6,7,8])

print(arr[1:5])

[3 4 5 2]


In [3]:
import numpy as np

arr = np.array([2,3,4,5,6,7,8,9])

print(arr[4:])

[6 7 8 9]


In [4]:
print(arr[:4])

[2 3 4 5]


<H3>Negative Slicing</H3>
Use the minus operator to refer to an index from the end:

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


<H3>STEP</H3>
Use the step value to determine the step of the slicing:

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [7]:
print(arr[::2])

[1 3 5 7]


<H3>Slicing 2-D Arrays</H3>

In [8]:
import numpy as np

arr = np.array([[1,3,5,7,9], [2,4,6,8,10]])

print(arr[1, 1:4])

[4 6 8]


In [9]:
print(arr[0:2, 2])

[5 6]


In [10]:
print(arr[0:2, 1:4])

[[3 5 7]
 [4 6 8]]
